version: '3.8'

services:
  app:
    container_name: study-rent-dev
    image: study-rent-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
